
# Configuration for microservice service registry (eureka server)
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true # by default it will be true even if don't write this line
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka
